export enum DOCUMENT_LOG_TYPE{
  
  CREATION_DATE,
  SETTLEMENT,
  DEPOSIT,
  AGENT_PAYMENT,
  ISSUE_INVOICE,
  CLOSE_DOCUMENT,
  CANCEL_DOCUMENT,
  ISSUE_CREDIT,
  ISSUE_SAMPLE,
  ISSUE_ORDER,
  ISSUE_RAINCHECK

}